# Generated by Django 3.2.4 on 2022-02-02 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220130_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
