# Generated by Django 3.2.4 on 2021-06-28 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FU', 'Furniture'), ('AR', 'Art'), ('PL', 'Plants'), ('OR', 'Organizing'), ('AP', 'Appliances')], help_text='Enter a category', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('store', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the final price of the deal', max_digits=10)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(help_text='Enter a brief description of the deal', max_length=1000)),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
                ('status', models.CharField(blank=True, choices=[('a', 'Active'), ('e', 'Expired'), ('i', 'Issue'), ('b', 'Broken')], default='a', help_text='Deal availability', max_length=1)),
                ('category', models.ManyToManyField(help_text='Select a category for this deal', to='catalog.Category')),
            ],
        ),
    ]
