# Generated by Django 3.2.4 on 2022-02-19 22:24

import catalog.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('living room', 'Living Room'), ('dining room', 'Dining Room'), ('kitchen', 'Kitchen'), ('bedroom', 'Bedroom'), ('hallway', 'Hallway')], help_text='Enter a category', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('website_url', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=200, null=True)),
                ('pinterest_url', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('header_image', models.ImageField(blank=True, default='/images/Walmart_ereceipt.PNG', upload_to=catalog.models.upload_to, verbose_name='Image')),
                ('title_tag', models.CharField(default='Shared Hallway', max_length=200)),
                ('store', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, null=True)),
                ('brand', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
                ('like_count', models.BigIntegerField(default='0')),
                ('status', models.CharField(blank=True, choices=[('a', 'Active'), ('e', 'Expired'), ('i', 'Issue'), ('b', 'Broken')], default='a', help_text='Deal availability', max_length=1)),
                ('author', models.ForeignKey(default='benji', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='catalog.Category')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='accounts.CustomUser')),
                ('content', models.TextField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.deal')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
