# Generated by Django 3.2.4 on 2021-07-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Living Room', 'Living Room'), ('Dining Room', 'Dining Room'), ('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Hallway', 'Hallway')], help_text='Enter a category', max_length=200),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
