# Generated by Django 3.2.4 on 2021-07-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_deal_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('living room', 'Living Room'), ('dining room', 'Dining Room'), ('kitchen', 'Kitchen'), ('bedroom', 'Bedroom'), ('hallway', 'Hallway')], help_text='Enter a category', max_length=200),
        ),
    ]
