# Generated by Django 3.2.4 on 2021-07-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_deal_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
