# Generated by Django 3.2.4 on 2021-07-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='accounts.CustomUser'),
        ),
    ]
