# Generated by Django 3.2.4 on 2021-07-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='snippet',
            field=models.CharField(default='Click to learn more', max_length=200),
        ),
    ]
