# Generated by Django 3.2.4 on 2021-08-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20210803_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.TextField(max_length=25),
        ),
    ]
