# Generated by Django 3.2.4 on 2021-10-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_deal_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['date_posted']},
        ),
    ]
