# Generated by Django 3.2.4 on 2021-10-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_deal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
