# Generated by Django 3.2.4 on 2022-01-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_deal_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='slug',
            field=models.SlugField(default='title', max_length=250, unique_for_date='date_posted'),
        ),
    ]
