# Generated by Django 3.2.4 on 2022-01-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_deal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='date_posted'),
        ),
    ]
