# Generated by Django 3.2.4 on 2022-02-09 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_alter_deal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
