# Generated by Django 3.2.4 on 2021-07-15 02:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_deal_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='category',
            field=models.ManyToManyField(to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='summary',
            field=models.TextField(max_length=1000),
        ),
    ]
