# Generated by Django 3.2.4 on 2021-07-20 15:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_deal_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
