# Generated by Django 3.2.4 on 2021-08-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_deal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
