# Generated by Django 3.2.4 on 2021-08-26 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0027_deal_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='deals', to=settings.AUTH_USER_MODEL),
        ),
    ]
